config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'home#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  resource :users, only: [] do
    resource :sign_up, controller: 'users/sign_up', only: %i[show create]
    resource :sign_in, controller: 'users/sign_in', only: %i[show create]
    resource :sign_out, controller: 'users/sign_out', only: %i[destroy]

    resources :activate, controller: 'users/activate', only: %i[show]
    resources :password_resets, controller: 'users/password_resets', except: %i[show destroy]

    resource :resend_activation_token, controller: 'users/resend_activation_token', only: %i[show create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  authenticates_with_sorcery!

  validates :email,
            uniqueness_without_deleted: true,
            email_format: true

  validates :password,
            length: { minimum: 8 },
            confirmation: true,
            if: :new_record_or_changes_password

  validates :password_confirmation,
            presence: true,
            if: :new_record_or_changes_password

  private

  def new_record_or_changes_password
    new_record? || changes[:crypted_password]
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  layout 'admin/layouts/application'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/activate_controller.rb
class Users::ActivateController < ApplicationController
  skip_before_action :require_login, raise: false

  def show
    # NOTE: id = activation_token
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      flash[:success] = t('view.users.activate.success')
      redirect_to users_sign_in_url
    else
      not_authenticated
    end
  end
end

app/controllers/users/password_resets_controller.rb
class Users::PasswordResetsController < UsersController
  skip_before_action :require_login, raise: false
  before_action -> { redirect_back fallback_location: root_path if logged_in? }

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: user_params[:email])

    @user.deliver_reset_password_instructions! if @user.present?

    flash[:success] = "#{User.human_attribute_name(:password)}変更確認メールを送信しました。\nメールに記載されたURLからパスワード変更を完了してください。"
    redirect_to root_url
  end

  def edit
    # NOTE: id = reset_password_token
    @token = params[:id]
    @user  = User.load_from_reset_password_token(params[:id])

    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    return not_authenticated if @user.blank?

    @user.password_confirmation = user_params[:password_confirmation]

    if @user.change_password!(user_params[:password])
      flash[:success] = "#{User.human_attribute_name(:password)}変更が完了しました。"
      redirect_to users_sign_in_url
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users/resend_activation_token_controller.rb
class Users::ResendActivationTokenController < ApplicationController
  skip_before_action :require_login, raise: false

  def show
    @user = User.new
  end

  def create
    @user = User.find_by(email: user_params[:email])
    return render :show unless @user.valid_password?(user_params[:password])

    if @user.activation_token.blank?
      flash[:error] = t('view.users.resend_activation_token.failure.already_activated')
      return redirect_to users_sign_in_url
    end

    UserMailer.activation_needed_email(@user).deliver_now
    flash[:success] = t('view.users.resend_activation_token.success')
    redirect_to users_sign_in_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users/sign_in_controller.rb
class Users::SignInController < ApplicationController
  skip_before_action :require_login, raise: false
  before_action -> { redirect_back fallback_location: root_path if logged_in? }

  def show
    @user = User.new
  end

  def create
    email, password = params[:user].values_at(:email, :password)

    @user = login(email, password)

    if @user.blank?
      @user = User.new(email: email).tap { |user| user.errors.add(:email, :not_found_or_invalid_password) }
      return render :show
    end

    redirect_back_or_to root_url
  end
end

app/controllers/users/sign_out_controller.rb
class Users::SignOutController < ApplicationController
  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/users/sign_up_controller.rb
class Users::SignUpController < UsersController
  skip_before_action :require_login, raise: false
  before_action -> { redirect_back fallback_location: root_path if logged_in? }

  def show
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    return render :show if @user.errors.present?

    flash[:success] = t('view.sign_up.success')
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-danger',
    warning: 'alert-warning',
    notice: 'alert-warning'
  }.freeze

  def flash_class_for(flash_type)
    FLASH_MSG[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/admin/dashboard/index.html.haml
%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.haml

app/views/admin/layouts/_header.html.haml
%header.main-header
  %a.logo{ href: admin_dashboard_path }
    %span.logo-mini
      %b> D
      LS
    %span.logo-lg
      %b #{Settings.service.name}
      Dashboard
  %nav.navbar.navbar-static-top{:role => "navigation"}
    %a.sidebar-toggle{"data-toggle" => "push-menu", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation

app/views/admin/layouts/_sidebar.html.haml
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar Menu
    %ul.sidebar-menu{"data-widget" => "tree"}
      %li.header 機能一覧
      / Optionally, you can add icons to the links
      %li.active
        %a{:href => "#"}
          %i.fa.fa-link
          %span Link
      %li
        %a{:href => "#"}
          %i.fa.fa-link
          %span Another Link
      %li.treeview
        %a{:href => "#"}
          %i.fa.fa-link
          %span Multilevel
          %span.pull-right-container
            %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li
            %a{:href => "#"} Link in level 2
          %li
            %a{:href => "#"} Link in level 2
    / /.sidebar-menu
  / /.sidebar

app/views/admin/layouts/application.html.haml
!!!
%html
  %head
    %title #{Settings.service.name}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    / Tell the browser to be responsive to screen width
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/

    = csrf_meta_tags
    = stylesheet_link_tag    'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'

  %body.hold-transition.skin-blue.sidebar-mini
    .wrapper
      = render 'admin/layouts/header'
      = render 'admin/layouts/sidebar'
      .content-wrapper
        %section.content-header
          %h1
            Page Header
            %small Optional description
          %ol.breadcrumb
            %li
              %a{:href => "#"}
                %i.fa.fa-dashboard
                Level
            %li.active Here
        %section.content.container-fluid
          = yield

      %footer.main-footer
        .pull-right.hidden-xs
          Anything you want
        %strong
          Copyright © 2016
        All rights reserved.

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_flash.html.erb
<%
  flash.each do |msg_type, message|
    next if msg_type == 'timedout'
    concat(content_tag(:div, class: "full-width-alert tl_c alert text-center alert-position #{flash_class_for(msg_type)} alert-dismissible fade in", role: 'alert') do
      concat (content_tag(:span) do
        concat content_tag(:span, "×", class: "close", "aria-hidden": true, data: { dismiss: "alert" })
        concat content_tag(:span, 'close', class: 'sr-only')
      end)
      concat simple_format(h(message))
    end)
    # "Added clearing of flash messages after initial page view" https://gist.github.com/suryart/7418454
    flash.clear
  end
%>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RocketDash
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/flash'
    .container
      .header.clearfix
        %nav
          %ul.nav.nav-pills.pull-right
            - if logged_in?
              %li
                = link_to 'Sign out', users_sign_out_path(@current_user), method: :delete, class: %w[text-danger]
            - else
              %li
                = link_to 'Sign up', users_sign_up_path, class: %w[btn btn-success]
              %li
                = link_to 'Sign in', users_sign_in_path, class: %w[btn btn-primary]
        %h3.text-muted
          = link_to RocketDash, root_path
      = yield

app/views/users/password_resets/create.html.haml
%h1 Users::PasswordResets#create
%p Find me in app/views/users/password_resets/create.html.haml

app/views/users/password_resets/edit.html.haml
%h1 #{User.human_attribute_name(:password)}変更

= simple_form_for @user, url: users_password_reset_path do |f|
  = f.input :password, as: :password
  = f.input :password_confirmation, as: :password
  = f.button :submit, "#{User.human_attribute_name(:password)}変更"

.container
  = link_to "登録確認メールを再送信する方はこちら", users_resend_activation_token_path

app/views/users/password_resets/new.html.haml
%h1 パスワードリセット

= simple_form_for @user, url: users_password_resets_path do |f|
  = f.input :email, as: :email
  = f.button :submit, "#{User.human_attribute_name(:password)}リセット"

.container
  = link_to "登録確認メールを再送信する方はこちら", users_resend_activation_token_path

app/views/users/resend_activation_token/show.html.haml
%h1 登録確認メール再送

= simple_form_for @user, url: users_resend_activation_token_path, method: :post do |f|
  = f.input :email, as: :email
  = f.input :password, as: :password
  = f.button :submit, '再送'

app/views/users/sign_in/show.html.haml
%h1 ログイン

= simple_form_for @user, url: users_sign_in_path do |f|
  = f.input :email, as: :email
  = f.input :password, as: :password
  = f.button :submit, 'ログイン'

.container
  = link_to "#{User.human_attribute_name(:password)}を忘れた方はこちら", new_users_password_reset_path
  = link_to "登録確認メールを再送信する方はこちら", users_resend_activation_token_path

app/views/users/sign_up/show.html.haml
%h1 #{User.model_name.human}登録

= simple_form_for @user, url: users_sign_up_path do |f|
  = f.input :email, as: :email
  = f.input :password, as: :password
  = f.input :password_confirmation, as: :password
  = f.button :submit, "#{User.model_name.human}登録"

.container
  = link_to "#{User.human_attribute_name(:password)}を忘れた方はこちら", root_path
  = link_to "登録確認メールを再送信する方はこちら", users_resend_activation_token_path